version: "3"
services:
  varnish:
    image: meanbee/magento2-varnish:latest
    hostname: ${PROJECT_HOSTNAME}
    ports:
      - 80
    environment:
      - VIRTUAL_HOST=${PROJECT_HOSTNAME}
      - VIRTUAL_PORT=80
      - HTTPS_METHOD=noredirect
      - CERT_NAME=default
    links:
      - web

  web:
    image: meanbee/magento2-nginx:1.9
    hostname: web.${PROJECT_HOSTNAME}
    ports:
      - 80
    volumes:
      - magento:/var/www/magento
      - ..:/src
    links:
      - fpm

  fpm:
    image: meanbee/magento2-php:7.0-fpm
    hostname: fpm.${PROJECT_HOSTNAME}
    ports:
      - 9000
    volumes:
      - magento:/var/www/magento
      - ..:/src
    environment:
      - ENABLE_SENDMAIL=true
      - PHP_ENABLE_XDEBUG
    links:
      - db

  cron:
    image: meanbee/magento2-php:7.0-cli
    hostname: cron.${PROJECT_HOSTNAME}
    command: run-cron
    volumes:
      - magento:/var/www/magento
      - ..:/src
    environment:
      - ENABLE_SENDMAIL=true
    links:
      - db

  cli:
    image: meanbee/magento2-php:7.0-cli
    command: /bin/true
    volumes:
      - magento:/var/www/magento
      - ..:/src
      - ~/.composer:/root/.composer
    environment:
      - COMPOSER_HOME=/root/.composer
      - COMPOSER_ALLOW_SUPERUSER=1
      - M2SETUP_INSTALL_DB=true
      - M2SETUP_VERSION=2.1.*
      - M2SETUP_USE_SAMPLE_DATA=true
      - M2SETUP_DB_HOST=db
      - M2SETUP_DB_NAME=magento2
      - M2SETUP_DB_USER=magento2
      - M2SETUP_DB_PASSWORD=magento2
      - M2SETUP_BASE_URL=https://${PROJECT_HOSTNAME}/
      - M2SETUP_BACKEND_FRONTNAME=admin
      - M2SETUP_ADMIN_FIRSTNAME=Admin
      - M2SETUP_ADMIN_LASTNAME=User
      - M2SETUP_ADMIN_EMAIL=admin@example.com
      - M2SETUP_ADMIN_USER=admin
      - M2SETUP_ADMIN_PASSWORD=password123
    links:
      - db

  db:
    image: mariadb:10
    ports:
      - 3306
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=magento2
      - MYSQL_USER=magento2
      - MYSQL_PASSWORD=magento2
      - MYSQL_DATABASE=magento2
      - TERM=dumb

  sync:
    image: cweagans/bg-sync
    volumes:
      - magento:/var/www/magento
      - ..:/src
    environment:
      - SYNC_SOURCE=/var/www/magento
      - SYNC_DESTINATION=/src/magento
      - SYNC_VERBOSE=1
      - SYNC_MAX_INOTIFY_WATCHES=64000
    privileged: true
    restart: on-failure

volumes:
  magento:
    # Magento source files
  dbdata:
    # Database table data
